project:
  type: website
  render:
    - "index.qmd"
    - "posts/*.md"
    - "posts/*.ipynb"
  resources:
    - "assets/"

website:
  description: "A blog built with Quarto"
  site-url: https://zhen8838.github.io
  title: "Zheng's Notes"
  favicon: assets/favicon.ico
  navbar: true
  comments:
    utterances:
      repo: zhen8838/zhen8838.github.io

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    highlight-style: github



